language: node_js
node_js:
  - '6.0.0'
before_install:
  - npm install -g jspm
  - npm install -g gulp
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - jspm -v
  - jspm install
  - npm install
script: 
  - npm run test

